networks:
  localdev:
    name: localdev

services:
  social-db-sql:
    container_name: social-db-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD?err}
    user: root
    ports:
      - "1433:1433"
    networks:
      - localdev
    volumes:
      - db-data:/var/opt/mssql/data
        
  social-api:
    container_name: social-api
    build:
      context: ./social-api/
    environment:
      - "Authentication:JwtOptions:Key=${JWT_KEY?err}"
    restart: always
    depends_on:
      - social-db-sql
    networks:
      - localdev

  social-frontend:
    container_name: social-frontend
    build: 
      context: ./social-frontend
    depends_on:
      - social-api

  battleships-server:
    container_name: battleships-server
    build:
      context: ./battleships/backend
    # environment:
    restart: always
    depends_on:
      - social-api
    ports:
      - "8000:8000"
    networks:
      - localdev
  
  battleships-client:
    container_name: battleships-client
    build:
      context: ./battleships/game-app-mui
    environment:
    depends_on:
      - battleships-server
    ports:
      - "3001:3000"
    networks:
      - localdev

volumes:
  db-data:
