version: '3'

services:
  social-frontend:
    build: ./social-frontend
    container_name: social-frontend
    ports:
      - 80:3000
  social-api:
    build: ./social
    container_name: social-api
    ports:
      - 5000:80
      - 5001:433